name: Release

on:
  push:
    branches: [ master ]
    #tags:
    #  - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        
      - name: Install nox
        uses: excitedleigh/setup-nox@1.0.0      
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Test
        run: |
          nox

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Datacker base image
        uses: docker/build-push-action@v2
        with:
          context: docker/.
          file: docker/Dockerfile
          push: true
          tags: |
            "${{ secrets.DOCKERHUB_USERNAME }}/datacker:latest"
            "${{ secrets.DOCKERHUB_USERNAME }}/datacker:0.1.0"
