name: Tests

on:
  push:
    branch: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install nox
        uses: excitedleigh/setup-nox@1.0.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Test, linter, & typing
        run: |
          nox

      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Get release version
        run: echo "RELEASE_VERSION=$(poetry version | awk '{print $2}')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker base image
        uses: docker/build-push-action@v2
        with:
          context: docker/.
          file: docker/Dockerfile
          push: false
          tags: |
            "${{ secrets.DOCKERHUB_USERNAME }}/datacker:latest"
            "${{ secrets.DOCKERHUB_USERNAME }}/datacker:${{ env.RELEASE_VERSION }}"
